### ISSUE TITLE
Is it possible to port this to Deta Space?

### ISSUE THREAD

**Issue by driftywinds** [forscht/watt#1]
Deta provides micros for anyone with an account to run webapps like this. It would be amazing if you could port this over onto it so the masses can use this app with their own domain. I believe the docs to the same are here - https://deta.space/docs/en/build/new-apps/

Please let me know if this is viable thanks!

**Comment by forscht** [comment]
Hey, It's not possible to run it behind deta apps since it requires you to listen on port 25 for incoming emails.
